<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">


  <xacro:property name="body_radius" value="0.3"/>      
  <xacro:property name="body_height" value="0.08"/>       
  <xacro:property name="arm_length" value="0.25"/>        
  <xacro:property name="arm_radius" value="0.01"/>       
  <xacro:property name="motor_radius" value="0.02"/>      
  <xacro:property name="motor_height" value="0.03"/>      
  <xacro:property name="propeller_radius" value="0.12"/>  
  <xacro:property name="propeller_thickness" value="0.005"/> 

  <link name="world"/>

  <joint name="base_link_joint" type="prismatic">
    <parent link="world"/>
    <child link="hexacopter_body"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-2.0" upper="2.0" effort="50.0" velocity="0.5"/>
  </joint>
  
  <link name="hexacopter_body">
    <inertial>
      <mass value="1.0"/> 
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.02"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${body_radius}" length="${body_height}"/>
      </geometry>
        <material name="brown">
            <color rgba="${222/255} ${207/255} ${195/255} 1.0"/>
        </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${body_radius}" length="${body_height}"/>
      </geometry>
    </collision>
  </link>


  <link name="arm_1">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
    </collision>
  </link>

  <joint name="arm_joint_1" type="fixed">
    <origin xyz="${(body_radius + arm_length/2)} 0 0" rpy="0 1.57 0"/>
    <parent link="hexacopter_body"/>
    <child link="arm_1"/>
  </joint>

  <link name="motor_1">
    <inertial>
      <mass value="0.05"/> 
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00005" ixy="0" ixz="0" iyy="0.00005" iyz="0" izz="0.00005"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${motor_radius}" length="${motor_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${motor_radius}" length="${motor_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="motor_joint_1" type="fixed">
    <origin xyz="0 0 ${arm_length/2}" rpy="0 4.71 0"/>
    <parent link="arm_1"/>
    <child link="motor_1"/>
  </joint>

  <link name="propeller_1">
    <visual>
      <geometry>
        <cylinder radius="${propeller_radius}" length="${propeller_thickness}"/>
      </geometry>
        <material name="green">
            <color rgba="0 1 0 1"/>
        </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${propeller_radius}" length="${propeller_thickness}"/>
      </geometry>
    </collision>
  </link>

  <joint name="propeller_joint_1" type="fixed">
    <origin xyz="0 0 ${motor_height/2 + propeller_thickness/2}" rpy="0 0 0"/>
    <parent link="motor_1"/>
    <child link="propeller_1"/>
  </joint>

  <link name="arm_2">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
    </collision>
  </link>

  <joint name="arm_joint_2" type="fixed">
    <origin xyz="${(body_radius + arm_length/2) * cos(1.047)} ${(body_radius + arm_length/2) * sin(1.047)} 0" rpy="0 1.57 1.047"/>
    <parent link="hexacopter_body"/>
    <child link="arm_2"/>
  </joint>

  <link name="motor_2">
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00005" ixy="0" ixz="0" iyy="0.00005" iyz="0" izz="0.00005"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${motor_radius}" length="${motor_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${motor_radius}" length="${motor_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="motor_joint_2" type="fixed">
    <origin xyz="0 0 ${arm_length/2}" rpy="0 4.71 0"/>
    <parent link="arm_2"/>
    <child link="motor_2"/>
  </joint>

  <link name="propeller_2">
    <visual>
      <geometry>
        <cylinder radius="${propeller_radius}" length="${propeller_thickness}"/>
      </geometry>
        <material name="red">
            <color rgba="1 0 0 1"/>
        </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${propeller_radius}" length="${propeller_thickness}"/>
      </geometry>
    </collision>
  </link>

  <joint name="propeller_joint_2" type="fixed">
    <origin xyz="0 0 ${motor_height/2 + propeller_thickness/2}" rpy="0 0 0"/>
    <parent link="motor_2"/>
    <child link="propeller_2"/>
  </joint>

  <link name="arm_3">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
    </collision>
  </link>

  <joint name="arm_joint_3" type="fixed">
    <origin xyz="${(body_radius + arm_length/2) * cos(2.094)} ${(body_radius + arm_length/2) * sin(2.094)} 0" rpy="0 1.57 2.094"/>
    <parent link="hexacopter_body"/>
    <child link="arm_3"/>
  </joint>

  <link name="motor_3">
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00005" ixy="0" ixz="0" iyy="0.00005" iyz="0" izz="0.00005"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${motor_radius}" length="${motor_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${motor_radius}" length="${motor_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="motor_joint_3" type="fixed">
    <origin xyz="0 0 ${arm_length/2}" rpy="0 4.71 0"/>
    <parent link="arm_3"/>
    <child link="motor_3"/>
  </joint>

  <link name="propeller_3">
    <visual>
      <geometry>
        <cylinder radius="${propeller_radius}" length="${propeller_thickness}"/>
      </geometry>
        <material name="green">
            <color rgba="0 1 0 1"/>
        </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${propeller_radius}" length="${propeller_thickness}"/>
      </geometry>
    </collision>
  </link>

  <joint name="propeller_joint_3" type="fixed">
    <origin xyz="0 0 ${motor_height/2 + propeller_thickness/2}" rpy="0 0 0"/>
    <parent link="motor_3"/>
    <child link="propeller_3"/>
  </joint>

  <link name="arm_4">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
    </collision>
  </link>

  <joint name="arm_joint_4" type="fixed">
    <origin xyz="-${(body_radius + arm_length/2)} 0 0" rpy="0 1.57 3.1416"/>
    <parent link="hexacopter_body"/>
    <child link="arm_4"/>
  </joint>

  <link name="motor_4">
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00005" ixy="0" ixz="0" iyy="0.00005" iyz="0" izz="0.00005"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${motor_radius}" length="${motor_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${motor_radius}" length="${motor_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="motor_joint_4" type="fixed">
    <origin xyz="0 0 ${arm_length/2}" rpy="0 4.71 0"/>
    <parent link="arm_4"/>
    <child link="motor_4"/>
  </joint>

  <link name="propeller_4">
    <visual>
      <geometry>
        <cylinder radius="${propeller_radius}" length="${propeller_thickness}"/>
      </geometry>
        <material name="red">
            <color rgba="1 0 0 1"/>
        </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${propeller_radius}" length="${propeller_thickness}"/>
      </geometry>
    </collision>
  </link>

  <joint name="propeller_joint_4" type="fixed">
    <origin xyz="0 0 ${motor_height/2 + propeller_thickness/2}" rpy="0 0 0"/>
    <parent link="motor_4"/>
    <child link="propeller_4"/>
  </joint>

  <link name="arm_5">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
    </collision>
  </link>

  <joint name="arm_joint_5" type="fixed">
    <origin xyz="${(body_radius + arm_length/2) * cos(4.1888)} ${(body_radius + arm_length/2) * sin(4.1888)} 0" rpy="0 1.57 4.1888"/>
    <parent link="hexacopter_body"/>
    <child link="arm_5"/>
  </joint>

  <link name="motor_5">
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00005" ixy="0" ixz="0" iyy="0.00005" iyz="0" izz="0.00005"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${motor_radius}" length="${motor_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${motor_radius}" length="${motor_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="motor_joint_5" type="fixed">
    <origin xyz="0 0 ${arm_length/2}" rpy="0 4.71 0"/>
    <parent link="arm_5"/>
    <child link="motor_5"/>
  </joint>

  <link name="propeller_5">
    <visual>
      <geometry>
        <cylinder radius="${propeller_radius}" length="${propeller_thickness}"/>
      </geometry>
        <material name="green">
            <color rgba="0 1 0 1"/>
        </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${propeller_radius}" length="${propeller_thickness}"/>
      </geometry>
    </collision>
  </link>

  <joint name="propeller_joint_5" type="fixed">
    <origin xyz="0 0 ${motor_height/2 + propeller_thickness/2}" rpy="0 0 0"/>
    <parent link="motor_5"/>
    <child link="propeller_5"/>
  </joint>

  <link name="arm_6">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
    </collision>
  </link>

  <joint name="arm_joint_6" type="fixed">
    <origin xyz="${(body_radius + arm_length/2) * cos(5.236)} ${(body_radius + arm_length/2) * sin(5.236)} 0" rpy="0 1.57 5.236"/>
    <parent link="hexacopter_body"/>
    <child link="arm_6"/>
  </joint>

  <link name="motor_6">
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00005" ixy="0" ixz="0" iyy="0.00005" iyz="0" izz="0.00005"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${motor_radius}" length="${motor_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${motor_radius}" length="${motor_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="motor_joint_6" type="fixed">
    <origin xyz="0 0 ${arm_length/2}" rpy="0 4.71 0"/>
    <parent link="arm_6"/>
    <child link="motor_6"/>
  </joint>

  <link name="propeller_6">
    <visual>
      <geometry>
        <cylinder radius="${propeller_radius}" length="${propeller_thickness}"/>
      </geometry>
        <material name="red">
            <color rgba="1 0 0 1"/>
        </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${propeller_radius}" length="${propeller_thickness}"/>
      </geometry>
    </collision>
  </link>

  <joint name="propeller_joint_6" type="fixed">
    <origin xyz="0 0 ${motor_height/2 + propeller_thickness/2}" rpy="0 0 0"/>
    <parent link="motor_6"/>
    <child link="propeller_6"/>
  </joint>
</robot>
