<?xml version="1.0"?>
<robot name="robot_arm" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find my_hexacopter)/urdf/gazebo_control.xacro"/>
  <!--<xacro:include filename="$(find my_hexacopter)/urdf/sensors.xacro"/>
  <xacro:include filename="$(find my_hexacopter)/urdf/my_hexacopter_simple.xacro"/>-->


  <!-- Fixed Joint to Connect Base Link to Hexacopter 
  <joint name="hexacopter_body_to_base_link" type="fixed">
    <parent link="hexacopter_body"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="3.14 0 0"/>
  </joint>-->

  <!-- Properties -->
  <xacro:property name="link_length" value="0.25"/>
  <xacro:property name="joint_radius" value="0.05"/>
  <xacro:property name="link_radius" value="0.03"/>
  <xacro:property name="gripper_length" value="0.1"/>
  <xacro:property name="link_mass" value="1.0"/>


<!-- World Link Definition -->
  <link name="world">
    <inertial>
      <mass value="0.0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
  </link>

  <!-- Fixed Joint to Attach Base Link to World -->
<joint name="base_to_world" type="fixed">
  <parent link="world"/>
  <child link="base_link"/>
  <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${0.1 / 2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="${link_radius + 0.02}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${0.1 / 2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.1" radius="${link_radius + 0.02}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.5"/>
      <origin xyz="0 0 ${0.1 / 2}" rpy="0 0 0"/>
      <inertia ixx="0.02" ixy="0.0" ixz="0.0" iyy="0.02" iyz="0.0" izz="0.02"/>
    </inertial>
  </link>

  <!-- Joint 1 -->
  <joint name="joint_1" type="revolute">
    <parent link="base_link"/>
    <child link="link_1"/>
    <origin xyz="0 0 ${0.01}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="5.0" velocity="0.5"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <!-- Link 1 -->
  <link name="link_1">
    <visual>
      <origin xyz="0 0 ${link_length / 2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${link_length / 2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${link_length}" radius="${link_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${link_mass}"/>
      <origin xyz="0 0 ${link_length / 2}" rpy="0 0 0"/>
      <inertia ixx="0.005433" ixy="0.0" ixz="0.0" iyy="0.005433" iyz="0.0" izz="0.00045"/>
    </inertial>
  </link>

  <!-- Joint 2 -->
  <joint name="joint_2" type="revolute">
    <parent link="link_1"/>
    <child link="link_2"/>
    <origin xyz="0 0.06 ${link_length - 0.03}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.5" upper="2.5" effort="5.0" velocity="0.5"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <!-- Link 2 -->
  <link name="link_2">
    <visual>
      <origin xyz="0 0 ${link_length / 2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="green">
        <color rgba="0 1 0 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${link_length / 2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${link_length}" radius="${link_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${link_mass}"/>
      <origin xyz="0 0 ${link_length / 2}" rpy="0 0 0"/>
      <inertia ixx="0.005433" ixy="0.0" ixz="0.0" iyy="0.005433" iyz="0.0" izz="0.00045"/>
    </inertial>
  </link>

  <!-- Joint 3 -->
  <joint name="joint_3" type="revolute">
    <parent link="link_2"/>
    <child link="link_3"/>
    <origin xyz="0 -0.06 ${link_length - 0.03}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="5.0" velocity="0.5"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <!-- Link 3 -->
  <link name="link_3">
    <visual>
      <origin xyz="0 0 ${link_length / 2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${link_length / 2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${link_length}" radius="${link_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${link_mass}"/>
      <origin xyz="0 0 ${link_length / 2}" rpy="0 0 0"/>
      <inertia ixx="0.005433" ixy="0.0" ixz="0.0" iyy="0.005433" iyz="0.0" izz="0.00045"/>
    </inertial>
  </link>

  <!-- Gripper Joint -->
  <joint name="gripper_joint" type="revolute">
    <parent link="link_3"/>
    <child link="gripper"/>
    <origin xyz="0 0 ${link_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-0.5" upper="0.5" effort="5.0" velocity="1.0"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <!-- Gripper Link -->
  <link name="gripper">
    <visual>
      <origin xyz="0 0 ${gripper_length / 2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${gripper_length}" radius="${link_radius + 0.01}"/>
      </geometry>
      <material name="orange">
        <color rgba="1 0.5 0 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${gripper_length / 2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${gripper_length}" radius="${link_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 ${gripper_length / 2}" rpy="0 0 0"/>
      <inertia ixx="0.0002167" ixy="0.0" ixz="0.0" iyy="0.0002167" iyz="0.0" izz="0.00009"/>
    </inertial>
  </link>

  <!-- Transmissions -->
  <transmission name="transmission_joint_1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_1">
      <hardwareInterface>position</hardwareInterface>
    </joint>
    <actuator name="motor_joint_1">
      <hardwareInterface>position</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="transmission_joint_2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_2">
      <hardwareInterface>position</hardwareInterface>
    </joint>
    <actuator name="motor_joint_2">
      <hardwareInterface>position</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="transmission_joint_3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_3">
      <hardwareInterface>position</hardwareInterface>
    </joint>
    <actuator name="motor_joint_3">
      <hardwareInterface>position</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>  
</robot>