controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_position_controller:
      type: position_controllers/JointGroupPositionController
      
joint_position_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
